### ISSUE TITLE
Why is 471808 parameters

### ISSUE THREAD

**Issue by HannH** [Zheng222/DMFN#2]
Hi, i noticed that there are 471808 parameters in DMFB in your paper. But accroding to your picture, I only get 3x3x256x64+64x64x3x3x7+256x1x1x256=471040, why it is 471808? By the way, I would appreciated it if you can release the code of whole model.

**Comment by Zheng222** [comment]
@HannH Hi, you ignored the bias parameter. 471040 + 64 + 64 x 7 + 256 = 471808. Since I can't go back to school at the moment, the code will be released later.

**Comment by HannH** [comment]
> @HannH Hi, you ignored the bias parameter. 471040 + 64 + 64 x 7 + 256 = 471808. Since I can't go back to school at the moment, the code will be released later.

thanks, I can't go back for work either, wish you luck.
