### ISSUE TITLE
A question about align loss

### ISSUE THREAD

**Issue by HannH** [Zheng222/DMFN#4]
Hello, I have a question about Equation 6,7 in your paper. In Equation 6, we get c_u_k by cumulating R along axis u,v , So why can we cumuylate along axis u,v again in Equation 7? In my opinion, the shape of c_u_k is (B,k), right?

**Comment by Zheng222** [comment]
@HannH Hello, in Eq. 6, the c_u_k  is coordinate expectation along axis u. The definition of expectation is the sum(variable *  probability distribution function). The shape of c_u_k is (B, 1).

**Comment by HannH** [comment]
> @HannH Hello, in Eq. 6, the c_u_k is coordinate expectation along axis u. The definition of expectation is the sum(variable * probability distribution function). The shape of c_u_k is (B, 1).

Thanks, but I still can not understand the symbol sigma(u,v) in Equation 7 since you said the shape of c_u_k is (B,1), I mean there is even no axis u or axis v in c_u_k to accumulate, right?

**Comment by Zheng222** [comment]
@HannH The updated equation 7 is shown as follows
![image](https://user-images.githubusercontent.com/24320162/75744049-0d49e400-5d4e-11ea-89ae-804d809ae339.png)

**Comment by HannH** [comment]
> @HannH The updated equation 7 is shown as follows
> ![image](https://user-images.githubusercontent.com/24320162/75744049-0d49e400-5d4e-11ea-89ae-804d809ae339.png)

**Comment by HannH** [comment]
Thanks for your reply
