### ISSUE TITLE
size and orientation of mask into discriminator

### ISSUE THREAD

**Issue by bhxvsh** [Zheng222/DMFN#6]
Hi, your method is amazing.
I am implementing your paper.
I just want to know how should be the input for the local discriminator.
The example given in the paper describes the square patched mask as input to the local discriminator, but I would like to know-how should be an input of the mask into the local discriminator when the patch is not of square size? the patch or mask might be shared all over the image pixels.

would like to hear from you soon
thanks!

**Comment by bhaveshIITB** [comment]
Hi
