### ISSUE TITLE
Format of custom masks

### ISSUE THREAD

**Issue by Nerdyvedi** [Zheng222/DMFN#9]
Hi, What format should custom masks be in ?
Like, what should be the values of the mask ?

**Comment by Zheng222** [comment]
@Nerdyvedi Hello
![60002](https://user-images.githubusercontent.com/24320162/99617489-6e3f5680-2a5a-11eb-990e-8fbe072225bd.png)
Like the above mask image,  white pixels (value = 1) denote masked region, and black pixels are known areas. This point has been explained in our paper. I will supplement the description of the testing procedure as soon as possible.
